language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd tests
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit

notifications:
  irc: "irc.freenode.net#xi-project"
